version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: multi_tenant_db_dev
      MYSQL_USER: django
      MYSQL_PASSWORD: django_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  web:
    image: fx0883/lipeaks_backend:latest
    restart: always
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your_production_secret_key_here
      - DB_NAME=multi_tenant_db_dev
      - DB_USER=django
      - DB_PASSWORD=django_password
      - DB_HOST=db
      - DB_PORT=3306
      - LOG_TO_CONSOLE=True
      - DJANGO_SETTINGS_MODULE=core.settings_docker
      # 超级管理员设置
      - CREATE_SUPERUSER=true
      - SUPERUSER_USERNAME=admin
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASSWORD=admin123456
      # CORS设置
      - CORS_ALLOWED_ORIGINS=http://localhost,http://frontend
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: fx0883/lipeaks_admin:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
